name: news_app_flutter_riverpod
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    another_flutter_splash_screen: ^1.2.1
    blurrycontainer: ^2.1.0
    cupertino_icons: ^1.0.8
    dartz: ^0.10.1
    dio: ^5.8.0+1
    flutter:
        sdk: flutter
    flutter_riverpod: ^2.6.1
    flutter_screenutil: ^5.9.3
    go_router: ^14.8.0
    google_fonts: ^6.2.1
    tab_indicator_styler: ^2.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/
